import test from "node:test";import assert from "node:assert/strict";import {updateIntervaloDiametro} from "../src/services/intervalo-diametro-services.ts";
const valido={desde_m:5,hasta_m:10,diametro_pulg:6,material_tuberia:"PVC" as const};
function dbCon(filas:Record<string,unknown>[][]){let i=0;return{query:async()=>({rows:filas[i++]??[]})};}
test("inexistente o ajeno devuelve null para 404 genérico",async()=>assert.equal(await updateIntervaloDiametro(1,99,valido,dbCon([[]])),null));
test("rango diámetro y material inválidos devuelven 400",async()=>{for(const dato of [{...valido,desde_m:10,hasta_m:5},{...valido,diametro_pulg:0},{...valido,material_tuberia:"Madera" as "PVC"}])await assert.rejects(updateIntervaloDiametro(1,2,dato,dbCon([])),(e:unknown)=>typeof e==="object"&&e!==null&&"statusCode" in e&&e.statusCode===400);});
test("profundidad y solapamiento devuelven 400",async()=>{await assert.rejects(updateIntervaloDiametro(1,2,{...valido,hasta_m:31},dbCon([[{id_intervalo_diametro_perforacion:2}],[{profundidad_final_m:30}]])),/profundidad/);await assert.rejects(updateIntervaloDiametro(1,2,valido,dbCon([[{id_intervalo_diametro_perforacion:2}],[{profundidad_final_m:30}],[{id_intervalo_diametro_perforacion:3}]])),/solapa/);});
test("excluye el propio intervalo y actualiza",async()=>{const fila={id_intervalo_diametro_perforacion:2,id_pozo:1,...valido};assert.deepEqual(await updateIntervaloDiametro(1,2,valido,dbCon([[{id_intervalo_diametro_perforacion:2}],[{profundidad_final_m:30}],[],[fila]])),fila);});
test("eliminación concurrente después de validar devuelve null",async()=>assert.equal(await updateIntervaloDiametro(1,2,valido,dbCon([[{id_intervalo_diametro_perforacion:2}],[{profundidad_final_m:30}],[],[],[]])),null));
test("rechazo atómico con registro vigente devuelve 400",async()=>await assert.rejects(updateIntervaloDiametro(1,2,valido,dbCon([[{id_intervalo_diametro_perforacion:2}],[{profundidad_final_m:30}],[],[],[{id_intervalo_diametro_perforacion:2}]])),/solapa o excede/));
