import fs from "node:fs/promises";
import path from "node:path";
import { deflateSync } from "node:zlib";
import { crearPDF } from "../src/pdf/pdf-generate.ts";
import type { ReportePozo } from "../src/services/generar-informe-consultas.ts";

const destino=process.argv[2]??path.resolve("output/rsp06g"); const fotoDir=path.join(destino,"fotos"); const id=9607;
await fs.mkdir(fotoDir,{recursive:true});
const base:ReportePozo={id_pozo:id,propietario:"Propietario de control visual",empresa:"Empresa de perforaciones",perforador:"Equipo técnico",sitio:"Salto",departamento:"Salto",localidad:"Salto",latitud:"-31.388123",longitud:"-57.960456",fecha_inicio:"2026-08-05",fecha_fin:"2026-08-06",profundidad_final_m:100,nivel_estatico_m:8,nivel_dinamico_m:12,caudal_estimado_lh:1800,metodo_sedimentario:"Rotación con descripción técnica extensa para verificar el flujo automático",metodo_rocoso:"Percusión",cementacion:"Registrada",desarrollo:"Registrado",introduccion:null,nombre_archivo:null,foto_url:null,litologia:[{desde_m:0,hasta_m:20,material:"Arena fina"},{desde_m:20,hasta_m:100,material:"Basalto rosado"}],diametros:[{desde_m:0,hasta_m:10,diametro_pulg:8,material_tuberia:"Acero"},{desde_m:10,hasta_m:100,diametro_pulg:6,material_tuberia:"Acero"}],filtros:[{desde_m:50,hasta_m:70,diametro_pulg:6,material_tuberia:"PVC"}],niveles_aporte:[{profundidad_m:60}]};
for(const caso of [{nombre:"sin-foto",reporte:base},{nombre:"foto-horizontal",reporte:{...base,foto_url:"protegida"},dim:[900,420]},{nombre:"foto-vertical",reporte:{...base,foto_url:"protegida"},dim:[420,900]}] as const){if(caso.dim)await fs.writeFile(path.join(fotoDir,`pozo-${id}.png`),png(...caso.dim));else await fs.rm(path.join(fotoDir,`pozo-${id}.png`),{force:true});const doc=await crearPDF(caso.reporte,id,{directorioFotos:fotoDir,mapa:{}});await fs.writeFile(path.join(destino,`${caso.nombre}.pdf`),await doc.save());}
const extenso={...base,litologia:Array.from({length:100},(_,i)=>({desde_m:i,hasta_m:i+1,material:`Estrato técnico ${i+1}`})),profundidad_final_m:100};await fs.writeFile(path.join(destino,"tablas-y-perfil-multipagina.pdf"),await(await crearPDF(extenso,id,{directorioFotos:fotoDir,mapa:{}})).save());
console.log(JSON.stringify({destino,casos:4}));
function png(width:number,height:number){const raw=Buffer.alloc((width*4+1)*height);for(let y=0;y<height;y++)for(let x=0;x<width;x++){const o=y*(width*4+1)+1+x*4;raw[o]=35;raw[o+1]=110+(y%80);raw[o+2]=155;raw[o+3]=255;}const h=Buffer.alloc(13);h.writeUInt32BE(width,0);h.writeUInt32BE(height,4);h[8]=8;h[9]=6;return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk("IHDR",h),chunk("IDAT",deflateSync(raw)),chunk("IEND",Buffer.alloc(0))]);}
function chunk(tipo:string,datos:Buffer){const n=Buffer.from(tipo),s=Buffer.alloc(datos.length+12);s.writeUInt32BE(datos.length,0);n.copy(s,4);datos.copy(s,8);s.writeUInt32BE(crc(Buffer.concat([n,datos])),datos.length+8);return s;}function crc(d:Buffer){let c=0xffffffff;for(const b of d){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^(0xedb88320&-(c&1));}return(c^0xffffffff)>>>0;}
