import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { myPool } from "../src/db/pool.ts";
import { eliminarFotoPersistida, reemplazarFotoPersistida } from "../src/services/foto-pozo-service.ts";

const fotos=path.resolve("public");const usuarios:number[]=[];let idPozo:number|null=null;
const jpg=Buffer.from([0xff,0xd8,0xff,0x01]);const png=Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]);
async function limpiarIntentosPrevios(){const pozos=await myPool.query("SELECT DISTINCT p.id_pozo FROM pozo p JOIN usuario u ON u.id_usuario IN(p.id_propietario,p.id_perforador) WHERE u.email::text LIKE 'rsp06ge-%@example.invalid'");for(const fila of pozos.rows){const id=Number(fila.id_pozo);await myPool.query("DELETE FROM pozo WHERE id_pozo=$1",[id]);for(const n of await fs.readdir(fotos).catch(()=>[]))if(n.startsWith(`pozo-${id}.`))await fs.rm(path.join(fotos,n),{force:true});const t=path.join(fotos,".trash");for(const n of await fs.readdir(t).catch(()=>[]))if(n.startsWith(`${id}-`)||n.includes(`-${id}-`))await fs.rm(path.join(t,n),{force:true});}await myPool.query("DELETE FROM usuario WHERE email::text LIKE 'rsp06ge-%@example.invalid'");}
async function esperarBloqueados(cantidad:number){for(let i=0;i<500;i++){const r=await myPool.query("SELECT count(*)::int AS cantidad FROM pg_locks WHERE locktype='advisory' AND classid=$1 AND objid=606 AND NOT granted",[idPozo]);if(Number(r.rows[0].cantidad)>=cantidad)return;await new Promise<void>((resolve)=>setImmediate(resolve));}throw new Error("Las operaciones no esperaron el advisory lock");}
async function preparar(extension:"jpg"|"png"|null){if(!idPozo)return;for(const n of await fs.readdir(fotos).catch(()=>[]))if(n.startsWith(`pozo-${idPozo}.`))await fs.rm(path.join(fotos,n),{force:true});if(extension)await fs.writeFile(path.join(fotos,`pozo-${idPozo}.${extension}`),extension==="jpg"?jpg:png);await myPool.query("UPDATE pozo SET foto_url=$2 WHERE id_pozo=$1",[idPozo,extension?"/foto":null]);}
async function reemplazar(extension:"jpg"|"png"){const buffer=extension==="jpg"?jpg:png;return reemplazarFotoPersistida(idPozo!,fotos,{buffer,extension},"/foto",async(client,url)=>{await client.query("UPDATE pozo SET foto_url=$2 WHERE id_pozo=$1",[idPozo,url]);return true;});}
async function ejecutarEnOrden(primera:()=>Promise<unknown>,segunda:()=>Promise<unknown>){const gate=await myPool.connect();await gate.query("BEGIN");await gate.query("SELECT pg_advisory_xact_lock($1::integer,606)",[idPozo]);const a=primera();await esperarBloqueados(1);const b=segunda();await esperarBloqueados(2);await gate.query("COMMIT");gate.release();await Promise.all([a,b]);}
async function comprobar(extension:"jpg"|"png"|null){const db=await myPool.query("SELECT foto_url FROM pozo WHERE id_pozo=$1",[idPozo]);const activos=(await fs.readdir(fotos)).filter((n)=>n.startsWith(`pozo-${idPozo}.`));assert.equal(db.rows[0].foto_url,extension?"/foto":null);assert.deepEqual(activos,extension?[`pozo-${idPozo}.${extension}`]:[]);}
await limpiarIntentosPrevios();
try{const roles=await myPool.query("SELECT id_rol,nombre FROM rol WHERE nombre=ANY($1::text[])",[["propietario","perforador"]]);const sitio=await myPool.query("SELECT id_sitio FROM sitio ORDER BY id_sitio LIMIT 1");for(const nombre of ["propietario","perforador"]){const rol=Number(roles.rows.find((r)=>r.nombre===nombre)?.id_rol);if(!rol||!sitio.rows[0])throw new Error("Faltan catálogos");const u=await myPool.query("INSERT INTO usuario(email,nombre,password,activo) VALUES($1,$2,$3,true) RETURNING id_usuario",[`rsp06ge-${randomUUID()}@example.invalid`,`Temporal ${nombre}`,"hash-no-utilizable"]);const id=Number(u.rows[0].id_usuario);usuarios.push(id);await myPool.query("INSERT INTO usuario_rol(id_usuario,id_rol) VALUES($1,$2)",[id,rol]);}
  const p=await myPool.query("INSERT INTO pozo(id_propietario,id_perforador,id_sitio,creado_por,profundidad_final_m) VALUES($1,$2,$3,$2,30) RETURNING id_pozo",[usuarios[0],usuarios[1],Number(sitio.rows[0].id_sitio)]);idPozo=Number(p.rows[0].id_pozo);await fs.mkdir(fotos,{recursive:true});
  await preparar("jpg");await ejecutarEnOrden(()=>eliminarFotoPersistida(idPozo!,fotos),()=>reemplazar("png"));await comprobar("png");
  await preparar("jpg");await ejecutarEnOrden(()=>reemplazar("png"),()=>eliminarFotoPersistida(idPozo!,fotos));await comprobar(null);
  await preparar("jpg");await ejecutarEnOrden(()=>reemplazar("png"),()=>reemplazar("jpg"));await comprobar("jpg");
  await preparar("jpg");await ejecutarEnOrden(()=>eliminarFotoPersistida(idPozo!,fotos),()=>eliminarFotoPersistida(idPozo!,fotos));await comprobar(null);
  console.log(JSON.stringify({ejecutada:true,eliminarLuegoReemplazar:true,reemplazarLuegoEliminar:true,dosReemplazos:true,dosEliminaciones:true,coherencia:true,sinHuerfanos:true}));
}finally{if(idPozo)await myPool.query("DELETE FROM pozo WHERE id_pozo=$1",[idPozo]);for(const id of usuarios.reverse())await myPool.query("DELETE FROM usuario WHERE id_usuario=$1",[id]);if(idPozo){for(const n of await fs.readdir(fotos).catch(()=>[]))if(n.startsWith(`pozo-${idPozo}.`))await fs.rm(path.join(fotos,n),{force:true});const t=path.join(fotos,".trash");for(const n of await fs.readdir(t).catch(()=>[]))if(n.startsWith(`${idPozo}-`)||n.includes(`-${idPozo}-`))await fs.rm(path.join(t,n),{force:true});}await myPool.end();}
